"""AUTH-2a: bcrypt password-hashing helpers.

Pure and import-light: depends ONLY on ``bcrypt``. No database, no network,
no FastAPI. Account persistence (create / get) lives in ``database.py`` so
api_server (AUTH-2b) can reach accounts through the database layer without
importing postgres_storage directly (Phase-0 import-discipline guard).

This module never logs, prints, or returns the plaintext password.
"""

from __future__ import annotations

import bcrypt


def hash_password(plain: str) -> str:
    """Return a bcrypt hash (utf-8 ``str``) for ``plain``.

    A fresh per-call salt is generated by ``bcrypt.gensalt()``. Raises
    ``ValueError`` on an empty/non-string password (callers validate first).
    The plaintext is never stored or logged.
    """
    if not isinstance(plain, str) or not plain:
        raise ValueError("password must be a non-empty string")
    hashed = bcrypt.hashpw(plain.encode("utf-8"), bcrypt.gensalt())
    return hashed.decode("utf-8")


def verify_password(plain: str, password_hash: str) -> bool:
    """Return True iff ``plain`` matches the stored bcrypt ``password_hash``.

    Returns False — never raises — on empty inputs or a malformed / non-bcrypt
    stored hash (bcrypt.checkpw raises ``ValueError`` on a bad salt/hash, which
    we swallow into a clean False).
    """
    if not plain or not password_hash:
        return False
    try:
        return bcrypt.checkpw(
            plain.encode("utf-8"), password_hash.encode("utf-8")
        )
    except (ValueError, TypeError):
        return False
